In [29]:
import numpy as np

In [30]:
# Write a NumPy program to create an array of all even integers from 30 to 70.
even_array = np.arange(30, 71, 2)
print("Array of even integers from 30 to 70:")
print(even_array)

Array of even integers from 30 to 70:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [31]:
# Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.
random_numbers = np.random.randn(15)
print("Array of 15 random numbers from standard normal distribution:")
print(random_numbers)

Array of 15 random numbers from standard normal distribution:
[-0.00652881 -1.02866381  1.08732095  0.18719801 -0.40280573 -0.82499899
  1.41430809  1.58632605 -0.34493778  0.75723406  0.25504669 -0.70076326
 -0.34467544  0.01323948 -0.34043317]


In [32]:
# How to compute the cross-product of two matrices in NumPy?
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
cross_product = np.cross(matrix1, matrix2)
print("Cross-product of two matrices:")
print(cross_product)

Cross-product of two matrices:
[[-10  20 -10]
 [-10  20 -10]
 [-10  20 -10]]


In [37]:
# How to compute the determinant of an array using NumPy?
matrix = np.array([[1, 2], [3, 4]])
determinant = np.linalg.det(matrix)
print("Determinant of the array:", determinant)

Determinant of the array: -2.0000000000000004


In [34]:
# How to create a 3x3x3 array with random values using NumPy?
random_3d_array = np.random.random((3, 3, 3))
print("Three Arrays of 3x3 with random values:")
print(random_3d_array)

Three Arrays of 3x3 with random values:
[[[0.75754274 0.58674589 0.71681823]
  [0.56884344 0.0190489  0.05667461]
  [0.0459114  0.83604148 0.94861582]]

 [[0.24942212 0.23885875 0.96759961]
  [0.93925254 0.04915042 0.59099618]
  [0.15379801 0.5905245  0.08043809]]

 [[0.19575092 0.132925   0.48621651]
  [0.53904953 0.89733793 0.0178834 ]
  [0.61728477 0.27361539 0.68033325]]]


In [35]:
# How to create a 5x5 array with random values and find the minimum and maximum values using NumPy?
random_5x5_array = np.random.random((5, 5))
min_value = np.min(random_5x5_array)
max_value = np.max(random_5x5_array)
print("5x5 array with random values:")
print(random_5x5_array)
print("Minimum value:", min_value)
print("Maximum value:", max_value)



5x5 array with random values:
[[0.41762427 0.86580644 0.36950823 0.98668249 0.67815496]
 [0.25201138 0.6778764  0.04714627 0.71065003 0.22276959]
 [0.33022839 0.74375239 0.46340417 0.7099854  0.2122998 ]
 [0.94473452 0.34940035 0.67404771 0.89802222 0.3559791 ]
 [0.83517986 0.65346949 0.66772445 0.34790656 0.71724264]]

Minimum value: 0.04714627440417252
Maximum value: 0.9866824918858135


In [36]:
# How to compute the mean, standard deviation, and variance of a given array along the second axis in NumPy?
given_array = np.array([[1, 2, 3], [4, 5, 6]])
mean = np.mean(given_array, axis=1)
std_deviation = np.std(given_array, axis=1)
variance = np.var(given_array, axis=1)
print("Mean along the second axis:", mean)
print("Standard deviation along the second axis:", std_deviation)
print("Variance along the second axis:", variance)


Mean along the second axis: [2. 5.]
Standard deviation along the second axis: [0.81649658 0.81649658]
Variance along the second axis: [0.66666667 0.66666667]
